enable xfs quota and add an xfs quota script example
rancher/local-path-provisioner pull request #126
Opened 2020-09-02 07:37 UTC by nicktming

it is unsecure since pod could write unlimited size for current local-path-provisoner, so i made some changes to enable xfs quota for clusters which has xfs. And this is also compatiable with non-xfs clusters.

2020-09-10 22:19 UTC, yasker requested changes

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +	"strconv"
It can be in the same section as `sync` and `time`.

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +	iSizeInBytes, _ := storage.AsInt64()
Better not ignore the error.

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +	logrus.Infof("got sizeInBytes: %v, storage: %v, value: %v", sizeInBytes, storage.String(), storage.Value())
Need to add volume name to the log.

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +							Name:      "xfs-quota-projects",
Hmm, those are too specific for XFS. Is there any way we can make it more generic?

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +					Args:    []string{filepath.Join(parentDir, volumeDir), strconv.FormatInt(sizeInBytes, 10)},
It's better if we can use `--size` parameter instead of piling them up, otherwise it's easy to mix up the sequence.

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +						Privileged: &enablePrivileged,
Because we need to access `/etc`? Seems unnecessary if the user is not running XFS.

2020-09-10 22:19 UTC, yasker commented on provisioner.go
> +					Args:    []string{filepath.Join(parentDir, volumeDir), strconv.FormatInt(sizeInBytes, 10)},
Also, this changes the input of the setup/teardown script format. We need to document the change.

2021-01-08 08:40 UTC, innobead commented
The need was resolved by #128 , closing.

2021-01-08 08:40 UTC, closed without merging